<a href="https://colab.research.google.com/github/Kehmisolar/Trainings-Projects/blob/main/Gomycode_project_work_kemisola.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

Write a program that will find all numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a list.

Hint: Consider using the range(#begin, #end) method.**bold text** 

In [ ]:
import math

In [ ]:
rang= range(2000, 3200) 
l=[]
for i in range(2000, 3201):
    if (i%7==0) and (i%5!=0):
        l.append(str(i))

print(','.join(l))


2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199


 Question 2
 
 Write a program that can compute the factorial of a given number. (The factorial of n is the product of all positive integers less than or equal to n.) For example: For factorial(5)= 5 x 4 x 3 x 2 x 1 the result is 120 (i.e. factorial (0)=1).

In [ ]:
def factorial(n) :
  if n < 0:
        print(error)
  elif n==1:
     return 1
  else:
    return n * factorial(n-1)


In [ ]:
factorial (7)

5040

Question 3 

With a given integer number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). Then, the program should print the dictionary. Suppose the following input is supplied to the program: 8 Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}  

In [ ]:

def sqr(x,y):
  dic = {}
  for i in range(x,y):
    dic.update({i : i*i})
    print(dic)

In [ ]:
sqr(1,8)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49}


Question 4 

Given a non-empty string and an integral n, return a new string where the char at index n has been removed. The value of n will be a valid index of a char in the original string (i.e. n will be in the range 0..len(str)-1 inclusive).

missing_char('kitten', 1) → 'ktten'    for example here we remove "i" which is located in the index 1

missing_char('kitten', 0) → 'itten'   here we remove "k" which is in the index 0

missing_char('kitten', 4) → 'kittn'   here we remove "e" which is in the index 4

In [ ]:
def remove_char(str,n):
    return str[:n] + str[n+1:]

In [ ]:
remove_char('puppy',0)

'uppy'

In [ ]:
remove_char('puppy',3)


'pupy'

In [ ]:
remove_char('puppy',4)

'pupp'

Question 5 







Write a NumPy program to convert a NumPy array into a Python list structure.

Expected output: 

Original array elements: [[0 1] [2 3] [4 5]] 

Array to list: [[0, 1], [2, 3], [4, 5]] 
 

Hint: We can use the to_list() function to ensure the conversion.

In [ ]:
import numpy as np


In [ ]:
y = np.array([[2,5],[4,9]])

In [ ]:
x = y.tolist()
x

[[2, 5], [4, 9]]

In [ ]:
z = np.array([[0,1],[0,1],[4,5]])

In [ ]:
A = z.tolist()
A

[[0, 1], [0, 1], [4, 5]]

Question 6

Write a NumPy program to compute the covariance matrix of two given arrays. 

Original array1: [0 1 2] 

Original array2: [2 1 0] 

Covariance matrix of the said arrays: [[ 1. -1.] [-1. 1.]]
 

Hint: We can use the np.cov() function to calculate the covariance between these two arrays

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [ ]:
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nCovariance matrix of the said arrays:\n",np.cov(x, y))



Original array1:
[0 1 2]

Original array1:
[2 1 0]

Covariance matrix of the said arrays:
 [[ 1. -1.]
 [-1.  1.]]


Question 7

Question: Write a program that calculates and prints the value according to the given formula: Q= Square root of [(2 * C * D)/H] 

The following are the fixed values of C and H: C is 50. H is 30. 

D is the variable whose values should be input into your program in a comma-separated sequence. (That means D contains more than value)

Example: Let's assume the following comma-separated input sequence is given to the program: 100,150,180 The output of the program should be 18,22,24 

To further explain this, we will obtain a result for each value of D:  Q1= Square root of [(2 * C * 100)/H] =18, Q2= Square root of [(2 * C * 150)/H] = 22 and Q3 = Square root of [(2 * C * 180)/H]  = 24

In [3]:
def sqroot(struct):
  c=50
  h=30
  roots = []
  # sqrt=[x for x in struct().split(',')]
  for d in struct:
    roots.append(int(round(2*c*d)/h)**0.5)
  return roots

In [4]:
sqroot([100,150,180])

[18.24828759089466, 22.360679774997898, 24.49489742783178]